const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getTags: (pannelloId) => ipcRenderer.invoke('tags:getAll', pannelloId),
  elencoCategorie: () => ipcRenderer.invoke('categorie:elenco'),
  elencoPannelli: () => ipcRenderer.invoke('pannelli:elenco'),
  creaPannello: (nome) => ipcRenderer.invoke('pannelli:crea', nome),
  rinominaPannello: (payload) => ipcRenderer.invoke('pannelli:rinomina', payload),
  eliminaPannello: (id) => ipcRenderer.invoke('pannelli:elimina', id),
  getTagsPerGestione: (pannelloId) => ipcRenderer.invoke('tags:getAllPerGestione', pannelloId),
  creaCategoria: (payload) => ipcRenderer.invoke('categorie:crea', payload),
  toggleAttivaCategoria: (payload) => ipcRenderer.invoke('categorie:toggleAttiva', payload),
  creaTag: (payload) => ipcRenderer.invoke('tag:crea', payload),
  toggleAttivoTag: (payload) => ipcRenderer.invoke('tag:toggleAttivo', payload),
  spostaOrdineTag: (payload) => ipcRenderer.invoke('tag:spostaOrdine', payload),
  spostaOrdineCategoria: (payload) => ipcRenderer.invoke('categorie:spostaOrdine', payload),
  eliminaCategoria: (id) => ipcRenderer.invoke('categorie:elimina', id),
  rinominaCategoria: (payload) => ipcRenderer.invoke('categorie:rinomina', payload),
  eliminaTag: (id) => ipcRenderer.invoke('tag:elimina', id),
  rinominaTag: (payload) => ipcRenderer.invoke('tag:rinomina', payload),
  spostaGenitoreTag: (payload) => ipcRenderer.invoke('tag:spostaGenitore', payload),
  creaOTrovaTagCategoria: (categoriaId) => ipcRenderer.invoke('tag:creaOTrovaPerCategoria', categoriaId),
  creaEvento: (payload) => ipcRenderer.invoke('eventi:crea', payload),
  elencoEventiPerPartita: (partitaId) => ipcRenderer.invoke('eventi:elencoPerPartita', partitaId),
  scambiaOrdineEventi: (payload) => ipcRenderer.invoke('eventi:scambiaOrdine', payload),
  aggiornaNotaEvento: (payload) => ipcRenderer.invoke('eventi:aggiornaNota', payload),
  riordinaGruppoEventi: (eventoIdsInOrdine) => ipcRenderer.invoke('eventi:riordinaGruppo', eventoIdsInOrdine),
  filtraEventi: (payload) => ipcRenderer.invoke('eventi:filtra', payload),
  ricercaGlobale: (filtri) => ipcRenderer.invoke('eventi:ricercaGlobale', filtri),

  selezionaVideo: () => ipcRenderer.invoke('video:seleziona'),

  statoLicenza: () => ipcRenderer.invoke('licenza:stato'),
  installaAggiornamentoOra: () => ipcRenderer.invoke('aggiornamento:installaOra'),
  onAggiornamentoDisponibile: (callback) => ipcRenderer.on('aggiornamento:disponibile', (_e, dati) => callback(dati)),
  onAggiornamentoProgresso: (callback) => ipcRenderer.on('aggiornamento:progresso', (_e, dati) => callback(dati)),
  onAggiornamentoPronto: (callback) => ipcRenderer.on('aggiornamento:pronto', (_e, dati) => callback(dati)),
  onAggiornamentoErrore: (callback) => ipcRenderer.on('aggiornamento:errore', (_e, dati) => callback(dati)),
  attivaLicenza: (codice) => ipcRenderer.invoke('licenza:attiva', codice),
  machineId: () => ipcRenderer.invoke('licenza:machineId'),
  accediGoogle: () => ipcRenderer.invoke('auth:accediGoogle'),
  leggiImpostazioniApp: () => ipcRenderer.invoke('impostazioniApp:leggi'),
  scriviImpostazioneApp: (payload) => ipcRenderer.invoke('impostazioniApp:scrivi', payload),
  sceglieCartellaVideo: () => ipcRenderer.invoke('video:sceglieCartella'),
  dimensioneCache: () => ipcRenderer.invoke('cache:dimensione'),
  svuotaCache: () => ipcRenderer.invoke('cache:svuota'),
  versioneApp: () => ipcRenderer.invoke('app:versione'),
  eliminaTuttiDatiLocali: () => ipcRenderer.invoke('datiLocali:eliminaTutto'),
  rimuoviTagDoppioni: () => ipcRenderer.invoke('tag:rimuoviDoppioni'),

  opzioniFiltriArchivio: () => ipcRenderer.invoke('archivio:opzioniFiltri'),
  elencoPartite: (filtri) => ipcRenderer.invoke('archivio:elencoPartite', filtri),
  elencoPartiteConConteggi: () => ipcRenderer.invoke('partite:elencoConConteggi'),
  eliminaPartita: (id) => ipcRenderer.invoke('partite:elimina', id),

  creaOTrovaSquadra: (nome) => ipcRenderer.invoke('squadre:creaOTrova', nome),
  creaOTrovaStagione: (label) => ipcRenderer.invoke('stagioni:creaOTrova', label),
  creaPartita: (payload) => ipcRenderer.invoke('partite:crea', payload),

  elencoSquadre: () => ipcRenderer.invoke('squadre:elenco'),
  creaSquadra: (payload) => ipcRenderer.invoke('squadre:crea', payload),
  eliminaSquadra: (id) => ipcRenderer.invoke('squadre:elimina', id),
  elencoGiocatoriPerSquadra: (squadraId) => ipcRenderer.invoke('giocatori:elencoPerSquadra', squadraId),
  creaGiocatore: (payload) => ipcRenderer.invoke('giocatori:crea', payload),
  aggiornaGiocatore: (payload) => ipcRenderer.invoke('giocatori:aggiorna', payload),
  spostaOrdineGiocatore: (payload) => ipcRenderer.invoke('giocatori:spostaOrdine', payload),
  ordinaGiocatoriPerRuolo: (squadraId) => ipcRenderer.invoke('giocatori:ordinaPerRuolo', squadraId),
  eliminaGiocatore: (id) => ipcRenderer.invoke('giocatori:elimina', id),
  eventiGiocatore: (giocatoreId) => ipcRenderer.invoke('giocatori:eventi', giocatoreId),

  elencoPresentazioni: () => ipcRenderer.invoke('presentazioni:elenco'),
  creaPresentazione: (nome) => ipcRenderer.invoke('presentazioni:crea', nome),
  eliminaPresentazione: (id) => ipcRenderer.invoke('presentazioni:elimina', id),
  aggiungiEventiAPresentazione: (payload) => ipcRenderer.invoke('presentazioni:aggiungiEventi', payload),
  clipPresentazione: (presentazioneId) => ipcRenderer.invoke('presentazioni:clip', presentazioneId),
  aggiornaClipPresentazione: (payload) => ipcRenderer.invoke('presentazioni:aggiornaClip', payload),
  elencoMomentiClip: (presentazioneEventoId) => ipcRenderer.invoke('disegniMomento:elencoPerClip', presentazioneEventoId),
  creaMomento: (payload) => ipcRenderer.invoke('disegniMomento:crea', payload),
  aggiornaMomento: (payload) => ipcRenderer.invoke('disegniMomento:aggiorna', payload),
  eliminaMomento: (id) => ipcRenderer.invoke('disegniMomento:elimina', id),
  mutaTutteClip: (payload) => ipcRenderer.invoke('presentazioni:mutaTutteClip', payload),
  applicaTestoAPiuClip: (payload) => ipcRenderer.invoke('presentazioni:applicaTestoAPiuClip', payload),
  rimuoviClipPresentazione: (id) => ipcRenderer.invoke('presentazioni:rimuoviClip', id),
  aggiungiSchermata: (payload) => ipcRenderer.invoke('presentazioni:aggiungiSchermata', payload),
  aggiornaSchermata: (payload) => ipcRenderer.invoke('presentazioni:aggiornaSchermata', payload),
  esportaPresentazione: (payload) => ipcRenderer.invoke('presentazioni:esporta', payload),
  onAvanzamentoExport: (callback) => {
    ipcRenderer.removeAllListeners('export:avanzamento'); // evita ascoltatori doppi tra un'esportazione e l'altra
    ipcRenderer.on('export:avanzamento', (_e, dati) => callback(dati));
  },

  scriviPngTemp: (dataUrl) => ipcRenderer.invoke('export:scriviPngTemp', dataUrl)
});
